[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log

[program:xvfb]
command=/usr/bin/Xvfb :1 -screen 0 1920x1080x24
autorestart=true
priority=10

[program:x11vnc]
command=/usr/bin/x11vnc -display :1 -forever -nopw -shared -rfbport 5900
autorestart=true
priority=20

[program:novnc]
command=/usr/share/novnc/utils/novnc_proxy --vnc localhost:5900 --listen 8080
autorestart=true
priority=30

[program:simulator]
command=bash -c "source /opt/ros/jazzy/setup.bash && source /root/ws/install/setup.bash && ros2 launch gazebo_sim launch.py use_sim_time:=true enable_rviz:=false"
environment=DISPLAY=":1",LIBGL_ALWAYS_SOFTWARE="1",RMW_IMPLEMENTATION="rmw_cyclonedds_cpp",GZ_SIM_RESOURCE_PATH="/root/ws/src/gazebo_sim/models/",CYCLONEDDS_URI="file:///cyclonedds.xml"
autorestart=false
priority=40
